### ISSUE TITLE
Maybe support LinkingTo as well?

### ISSUE THREAD

**Issue by eddelbuettel** [ikosmidis/cranly#1]
When I build (much simpler) dependencies via the tools package, I follow their usual pattern of (and here I quote from the help for `tools::package_dependencies`)

```
   which: a character vector listing the types of dependencies, a
          subset of ‘c("Depends", "Imports", "LinkingTo", "Suggests",
          "Enhances")’.  Character string ‘"all"’ is shorthand for that
          vector, character string ‘"most"’ for the same vector without
          ‘"Enhances"’.
```

and tend to pick either 'all' or 'most' -- or just stick with the default value of the more explicit narrower set of `c("Depends", "Imports", "LinkingTo")`.

For packages like Rcpp and BH that matters a lot as most of the 'edges' in the graph are compile-time via LinkingTo, rather than via depended-upon or imported R code.

That said, awesome looking package :)   This will be nice to have around.

**Comment by ikosmidis** [comment]
Ah yes; that's important thanks. Full LinkingTo support is now on GitHub and will be on CRAN in the next release in a few weeks. 

<img width="909" alt="screen shot 2018-03-29 at 01 15 17" src="https://user-images.githubusercontent.com/15086307/38062978-bec05e8a-32ee-11e8-8cdc-d46de7317c73.png">

**Comment by eddelbuettel** [comment]
Nice.  Thank you.

Can your extractors also combine, ie do what CRAN does and use 

      Depends OR Imports OR LinkingTo 

all of which are hard dependencies?

**Comment by ikosmidis** [comment]
Yes. I wrote the plot method for summary to be totally agnostic to the statistic to be bar-plotted. So, (using the development version for now) you can do

```
library("cranly")
package_db <- clean_CRAN_db()
package_network <- build_network(package_db)
package_summaries <- summary(package_network, advanced = FALSE)
package_summaries$n_hard <- with(package_summaries, { 
                                        n_linked_by + n_depended_by + n_imported_by
})
plot(package_summaries, top = 30, according_to = "n_hard")
```

Is this what you are after?

<img width="926" alt="screen shot 2018-03-29 at 03 33 37" src="https://user-images.githubusercontent.com/15086307/38066972-3fe1cd7e-3302-11e8-8345-bb86a50d7a54.png">

**Comment by eddelbuettel** [comment]
Excellent -- that corresponds to the result we get via the [pagerank](https://github.com/andrie/pagerank) package by @andrie.   Maybe add a filter to remove R Base / R Recommended packages?

**Comment by ikosmidis** [comment]
Yes. Subsetting according to base is already in my todo for next release with moderate priority. 

Opened a new issue on this #2.

**Comment by ikosmidis** [comment]
Done in #2
