### ISSUE TITLE
visualise dependence trees

### ISSUE THREAD

**Issue by ikosmidis** [ikosmidis/cranly#3]

**Comment by ikosmidis** [comment]
Build package dependence trees with cranly

```
library("cranly")
p_db <- tools::CRAN_package_db()
package_db <- clean_CRAN_db(p_db)
package_network <- build_network(package_db)
## tidyverse dependence tree with legend and title
tidyverse_tree <- build_dependence_tree(package_network, package = "tidyverse")
plot(tidyverse_tree, , legend = TRUE, title = TRUE)
## tibble dependence tree
tibble_tree <- build_dependence_tree(package_network, package = "tibble")
plot(tibble_tree)
## PlackettLuce dependence tree excluding base and recommended packages
pl_tree <- build_dependence_tree(package_network, package = "PlackettLuce")
plot(pl_tree, base = FALSE, recommended = FALSE)
```
<img width="498" alt="screen shot 2018-03-30 at 22 57 34" src="https://user-images.githubusercontent.com/15086307/38155173-20a48aba-346e-11e8-85b6-55a5aed45c96.png">
<img width="773" alt="screen shot 2018-03-30 at 22 55 31" src="https://user-images.githubusercontent.com/15086307/38155175-20efb33c-346e-11e8-80a3-54c9c1fc8203.png">
<img width="754" alt="screen shot 2018-03-30 at 22 55 18" src="https://user-images.githubusercontent.com/15086307/38155176-21394d62-346e-11e8-93eb-1c1c4e13505f.png">

**Comment by nacnudus** [comment]
Thanks very much for this!

I expect you already know, but to get the code snippet above to work at the moment, you have to replace `build_dependency_tree` with `dependence_tree.cranly_network`.

**Comment by ikosmidis** [comment]
Indeed; I hadn't pushed the latest changes. Should be working as advertised now. Thanks, -I
